version: "3"
services:
  redis:
    image: redis:latest
    restart: always
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - my_shared_network
  postgresql:
    image: postgres:latest
    container_name: postgres_server
    ports:
      - "5432:5432"
    environment:
       - POSTGRES_DB=postgres
       - POSTGRES_USER=root
       - POSTGRES_PASSWORD=123456
    volumes:
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_shared_network
  pgadmin:
    image: dpage/pgadmin4:9.0.0
    container_name: pgadmin_server
    environment:
      PGADMIN_DEFAULT_EMAIL: mhthrh@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "900:80"
    networks:
      - my_shared_network
networks:
  my_shared_network:
    external: true

